[package]
name = "actix-web-benchmark"
version = "0.1.0"
authors = ["envy124 <pkgsail.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
